### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by richo** [liquidx/CoreBluetoothPeripheral#1]
I'd like to use your code.. it may or may not end up in something vaguely commercial. What's the license on it?

**Comment by liquidx** [comment]
Hey Richo,

You can treat the code as licensed under the Apache v2 license.

I'll add a license file shortly to clarify.

On Sat, Nov 16, 2013 at 4:46 AM, Richo Healey notifications@github.comwrote:

> I'd like to use your code.. it may or may not end up in something vaguely
> commercial. What's the license on it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/liquidx/CoreBluetoothPeripheral/issues/1
> .

## 

Alastair Tse
Phone: US: +1-415-230-1363
Twitter: @liquidx
Web: http://liquidx.net/
Gtalk: alastairtse@gmail.com

**Comment by richo** [comment]
Just saw that you added the license text. Thanks!
